### ISSUE TITLE
Federated polls cause original post to be duplicated in the timeline

### ISSUE THREAD

**Issue by GreenMan-Network** [bonfire-networks/bonfire-app#1440]
Hi everyone!

I'm continuing to test my new instance and I've noticed something that may be a bug in how replies from remote servers are rendered on the dashboard/home timeline.

**Describe the bug**
When a followed remote account's post receives multiple replies on its home instance, the original post is duplicated in my Bonfire home timeline for each reply, flooding the feed with the same content.

**To Reproduce**
1. Follow an active, remote Fediverse account (e.g., @nextcloud@mastodon.xyz).
2. Wait for that account to make a post that receives many replies on its original server.
3. View your own home dashboard on your Bonfire instance (at /dashboard).
4. See error: The original post from the remote account appears repeatedly in the timeline, once for each remote reply (screenshot below).

**Expected behavior**
- The remote post should appear only once in my home timeline.
- Any replies to it from the remote server should either be handled silently (by updating a reply counter on the single post entry) or be visible only within the conversation thread.
- The timeline should not be flooded with duplicates of the original post.

**Screenshots**
<img width="420" height="896" alt="Image" src="https://github.com/user-attachments/assets/7b6b43e2-4d33-48ad-a293-03212481dbc6" />

**Bonfire environment (please complete the following information):**
- Running env: prod with docker image
- Running with Co-op Cloud and/or Docker?: Docker only (manual docker-compose setup)
- Running version (check on your instance's sidebar): 1.0.0-rc.2.1
- Running flavour: social (with federation enabled in the admin panel)
- Running any extra/forked extensions: none

**Client device (please complete the following information):**
- Device: Desktop PC
- OS: Debian 12
- Browser: chrome
- Browser Version: Version 138.0.7204.100 (Official Build) (64-bit)

**Comment by mayel** [comment]
Hmm this looks like an issue we had specifically with polls that I thought was fixed in https://github.com/bonfire-networks/bonfire-app/issues/1368 but either that was after the version you're running or there's still cases where it happens, will have to check. Thanks for the detailed report!

**Comment by GreenMan-Network** [comment]
Hi there,

Just wanted to provide an update on this issue with some new findings that might help pinpoint the problem.

The timeline flooding is still happening on my feed. I did some more investigation and I've been able to identify a more specific trigger: the bug seems to be related to Polls.

Here's the scenario:
1. I am following a remote account that created a poll (e.g., from mastodon.matrix.org).
2. On my Bonfire instance (looking at the "Remote" timeline, this single poll post is duplicated dozens of times in the feed, making it unusable.

<img width="1215" height="884" alt="Image" src="https://github.com/user-attachments/assets/e44115ed-2e0e-4a13-9834-34c66a4e5c55" />

3. When I click on any of these duplicate entries, it opens the "Discussion" view on my server, but it's empty—none of the replies or the poll results/options are displayed.

<img width="1235" height="852" alt="Image" src="https://github.com/user-attachments/assets/ff061f25-fa46-4d4d-bed0-1c554bb8227b" />

4. When I check the original post on the remote server, I can see it's a normal poll with many votes and some comments.

<img width="1224" height="897" alt="Image" src="https://github.com/user-attachments/assets/cf1b3641-c746-4957-98e3-267d85fa2d3b" />

My hypothesis is that my instance is receiving an ActivityPub event for every single vote cast on the remote poll. It seems Bonfire is rendering a new instance of the original post in the timeline for each "vote" activity, instead of just updating the poll results on the single, original post entry.

I hope this new information is helpful for debugging! Let me know if there's anything I can do to help test a potential fix. Thanks!

**Comment by ivanminutillo** [comment]
thanks for reporting! this has been fixed in prev release
